# See https://pre-commit.com for more information
# Install locally: pip install pre-commit && pre-commit install
# Run on all files: pre-commit run --all-files

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml

  # Ruff for fast linting and formatting suggestions
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff
        args: ["--fix"]  # Autofix trivial issues where possible
      - id: ruff-format

  # Black for code formatting (kept for compatibility with existing style)
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3

  # Flake8 for additional linting rules
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
