name: 'Setup Python and Dependencies'
description: 'Sets up Python environment, caches dependencies, and installs requirements'
author: 'darkprinx'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.11'
  requirements-file:
    description: 'Path to requirements file'
    required: false
    default: 'requirements.txt'
  cache-key-prefix:
    description: 'Prefix for cache key'
    required: false
    default: 'pip'

runs:
  using: 'composite'
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Cache dependencies
      id: cache-dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-${{ inputs.cache-key-prefix }}-${{ hashFiles(format('**/{0}', inputs.requirements-file)) }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.cache-key-prefix }}-

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ inputs.requirements-file }}

    - name: Display Python version
      shell: bash
      run: python --version

    - name: Display pip list
      shell: bash
      run: |
        pip list
