# Generated by Django 4.1.4 on 2022-12-21 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('title', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('active', 'active'), ('closed', 'closed')], default='active', max_length=32)),
                ('ballot_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prize_money', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('participants', models.ManyToManyField(blank=True, null=True, related_name='registered_lotteries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lottery_event',
                'managed': True,
            },
        ),
    ]
