# Generated by Django 4.1.4 on 2022-12-21 03:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lottery_events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotteryevent',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='participated_lotteries', to=settings.AUTH_USER_MODEL),
        ),
    ]
