# Generated by Django 4.1.4 on 2022-12-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_events', '0002_alter_lotteryevent_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotteryevent',
            name='created_at',
            field=models.DateField(auto_now=True, db_index=True),
        ),
    ]
