# Generated by Django 4.1.4 on 2022-12-21 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_events', '0002_ballot'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotteryevent',
            name='winning_ballot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winning_lottery', to='lottery_events.ballot'),
        ),
    ]
