# Generated by Django 6.0.1 on 2026-02-05 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bought_at', models.DateTimeField(auto_now_add=True)),
                ('ballot_number', models.CharField(max_length=128)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_ballots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ballot',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('closed', 'Closed')], default='active', max_length=32)),
                ('ballot_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prize_money', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('participants', models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL)),
                ('winning_ballot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winning_ballot', to='event.ballot')),
            ],
            options={
                'db_table': 'event',
                'ordering': ('-created_at',),
                'managed': True,
                'indexes': [models.Index(fields=['created_at'], name='event_created_989bde_idx'), models.Index(fields=['status'], name='event_status_c263a9_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ballot_price__gte', 0)), name='ballot_price_non_negative'), models.CheckConstraint(condition=models.Q(('prize_money__gte', 0)), name='prize_money_non_negative')],
            },
        ),
    ]
