name: 'Run Code Quality Checks: Pre-commit, Ruff, Bandit, (optional) MyPy'
description: 'Runs linting and code quality/security checks for Python projects'
author: 'darkprinx'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.11'
  run-pre-commit:
    description: 'Whether to run pre-commit hooks'
    required: false
    default: 'true'
  run-pip-audit:
    description: 'Whether to run pip-audit vulnerability scan'
    required: false
    default: 'true'

outputs:
  pre-commit-result:
    description: 'Pre-commit check result'
    value: ${{ steps.pre-commit-check.outcome }}
  pip-audit-result:
    description: 'pip-audit dependency vulnerability scan result'
    value: ${{ steps.pip-audit-scan.outcome }}

runs:
  using: 'composite'
  steps:
    - name: Run pre-commit hooks
      id: pre-commit-check
      if: inputs.run-pre-commit == 'true'
      shell: bash
      continue-on-error: false
      run: |
        echo 'Running pre-commit on all files...'
        pre-commit run --all-files --show-diff-on-failure --color always

    - name: Run pip-audit vulnerability scan
      id: pip-audit-scan
      if: inputs.run-pip-audit == 'true'
      shell: bash
      continue-on-error: true
      run: |
        echo 'Running pip-audit (Python dependency vulnerabilities)...'
        pip-audit

    - name: Summary
      shell: bash
      run: |
        echo '### Code Quality Check Results' >> "$GITHUB_STEP_SUMMARY"
        echo '' >> "$GITHUB_STEP_SUMMARY"
        echo "- Pre-commit: ${{ steps.pre-commit-check.outcome || 'skipped' }}" >> "$GITHUB_STEP_SUMMARY"
        echo "- pip-audit: ${{ steps.pip-audit-scan.outcome || 'skipped' }}" >> "$GITHUB_STEP_SUMMARY"
