name: 'Run tests with pytest'
description: 'Runs pytest with coverage for Django project'
author: 'darkprinx'

inputs:
  coverage-report-format:
    description: 'Coverage report format (term-missing, xml, html)'
    required: false
    default: 'term-missing'
  upload-coverage:
    description: 'Whether to upload coverage to Codecov'
    required: false
    default: 'false'
  codecov-token:
    description: 'Codecov token for uploading coverage'
    required: false
    default: ''
  additional-pytest-args:
    description: 'Additional arguments to pass to pytest'
    required: false
    default: ''

outputs:
  coverage-file:
    description: 'Path to coverage file if generated'
    value: ${{ steps.set-coverage-path.outputs.coverage-path }}

runs:
  using: 'composite'
  steps:
    - name: Run tests
      id: run-tests
      shell: bash
      run: |
        pytest --cov=. --cov-report=${{ inputs.coverage-report-format }} ${{ inputs.additional-pytest-args }} | tee pytest-output.txt

    - name: Generate coverage summary
      if: always()
      shell: bash
      run: |
        echo "## Coverage Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        if [ -f "pytest-output.txt" ]; then
          # Extract coverage summary from pytest output
          grep -A 20 "^-.*-$" pytest-output.txt | tail -n 15 >> $GITHUB_STEP_SUMMARY
        else
          echo "No test output found" >> $GITHUB_STEP_SUMMARY
        fi
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

    - name: Generate XML coverage report
      if: inputs.upload-coverage == 'true'
      shell: bash
      run: |
        pytest --cov=. --cov-report=xml

    - name: Set coverage path
      id: set-coverage-path
      shell: bash
      run: |
        if [ -f "coverage.xml" ]; then
          echo "coverage-path=coverage.xml" >> $GITHUB_OUTPUT
        else
          echo "coverage-path=" >> $GITHUB_OUTPUT
        fi

    - name: Upload coverage to Codecov
      if: inputs.upload-coverage == 'true' && inputs.codecov-token != ''
      uses: codecov/codecov-action@v5
      with:
        token: ${{ inputs.codecov-token }}
        files: ./coverage.xml
        fail_ci_if_error: false

    - name: Show details of coverage path
      shell: bash
      run: |
        echo "Coverage path: ${{ steps.set-coverage-path.outputs.coverage-path }}"