name: Code Quality

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint and Code Style
    runs-on: ubuntu-latest
    # Run as non-blocking initially to introduce checks without breaking pipeline.
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install ruff flake8 black

      - name: Ruff (lint)
        run: |
          ruff check .

      - name: Flake8
        run: |
          flake8 .

      - name: Black (check only)
        run: |
          black --check .

      - name: Install pre-commit and tools
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Run pre-commit on all files
        run: |
          pre-commit run --all-files --show-diff-on-failure --color always