name: Dev CI Workflow

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  reusable-workflow:
    uses: ./.github/workflows/reusable.yml

  code-quality-check:
    name: Code quality & security checks
    runs-on: ubuntu-latest
    # Run as non-blocking initially to introduce checks without breaking pipeline.
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ruff (lint)
        run: |
          ruff check .

      - name: Run pre-commit on all files
        run: |
          pre-commit run --all-files --show-diff-on-failure --color always

#      - name: Security scan with Bandit    ### use when needed
#        run: bandit -r .

      - name: Audit dependencies with pip-audit
        run: safety scan --full-report

  test:
    runs-on: ubuntu-latest
    outputs:
      date_output: ${{ steps.test_output.outputs.date }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests (pytest)
        id: run_tests
        run: |
          pytest --cov=. --cov-report=term-missing

      - name: Run tests (pytest) with coverage report
        if: always()
        run: |
          pytest --cov=. --cov-report=xml

      - name: Upload artifacts
        if: failure() && steps.run_tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

      - name: Show artifacts # for learning purpose on artifacts
        run: ls -l

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Test output  # for learning purpose on outputs
        id: test_output
        run: |
          echo "date=$(date)" >> $GITHUB_OUTPUT


  post-build: # for testing cache dependencies installation only
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip- 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


  deploy:
    runs-on: ubuntu-latest
    needs: test # can have multiple jobs like [test, xyz]
    steps:
      - name: Get test coverage artifact  # for learning purpose on artifacts
        uses: actions/download-artifact@v4
        with:
          name: coverage-report

      - name: Show artifacts # for learning purpose on artifacts
        run: ls -l

      - name: Use date output  # for learning purpose on outputs
        run: |
          echo "The date is: ${{ needs.test.outputs.date_output }}"