name: Tests

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests (pytest)
        run: |
          pytest -q

  deploy:
    runs-on: ubuntu-latest
    needs: test # can have multiple jobs like [test, xyz]
    steps:
      - name: Deploy
        run: echo "Deploying..."